services:
  mysql:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keploydb
    networks:
      - keploy-net

networks:
  keploy-net:
    external: true
